In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

#basic operations
print ("array a:",a)
print ("array b:",b)
print("sum of array:",np.add(a,b))
print("difference:",np.subtract(a,b))
print("product:",np.multiply(a,b))
print("division:",np.divide(a,b))
print("square:",np.sqrt(a))
print("expo:",np.exp(a))

#aggregation op
print("minimum value a:",np.min(a))
print("maximum value a:",np.max(b))
print("mean value a:",np.mean(a))
print("standard value a:",np.std(b))
print("sum of all ele value a:",np.sum(a))

#reshaping array
c=np.array([[1,2],[3,4],[5,6]])
print("array c:")
print(c)
print("reshapd array c(2 rows,3 columns):")
print(np.reshape(c,(2,3)))

#transposing array
d=np.array([[1,2,3],[4,5,6]])
print("array d:")
print("transposed array d:")
print(np.transpose(d))

array a: [1 2 3 4 5]
array b: [ 6  7  8  9 10]
sum of array: [ 7  9 11 13 15]
difference: [-5 -5 -5 -5 -5]
product: [ 6 14 24 36 50]
division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
square: [1.         1.41421356 1.73205081 2.         2.23606798]
expo: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
minimum value a: 1
maximum value a: 10
mean value a: 3.0
standard value a: 1.4142135623730951
sum of all ele value a: 15
array c:
[[1 2]
 [3 4]
 [5 6]]
reshapd array c(2 rows,3 columns):
[[1 2 3]
 [4 5 6]]
array d:
transposed array d:
[[1 4]
 [2 5]
 [3 6]]
